# Generated by Django 5.2.7 on 2026-01-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_id_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.RemoveField(
            model_name='pass',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='pass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_type',
            field=models.CharField(choices=[('REFILL', 'Wallet Refill'), ('PURCHASE', 'Pass Purchase'), ('TICKET', 'Bus Ticket')], max_length=20),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='core.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='core.city')),
            ],
        ),
    ]
