# Generated by Django 5.2.7 on 2026-01-21 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_city_remove_pass_valid_until_pass_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_data', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('used_time', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
