# Generated by Django 5.2.7 on 2026-01-21 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_city_state_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='route',
            name='bus_number',
            field=models.CharField(default='BUS-001', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='route',
            name='gate',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
