# Generated by Django 5.2.7 on 2026-01-21 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_route_arrival_time_route_bus_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
